template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "sma"
__UND2C_TRG__ = "sv"
__UNDEFINED_SOURCE__ = "South Saami"
__UNDEFINED_TARGET__ = "Swedish"
__UND_SRC__ = "sma"
__UND_TRG__ = "swe"
